### ISSUE TITLE
Unable to drag to LaunchBox

### ISSUE THREAD

**Issue by diversys** [humdingerb/quicklaunch#13]
as in title...

**Comment by humdingerb** [comment]
I can't reproduce...

**Comment by diversys** [comment]
This is still the case. I can't reopen tho.

**Comment by humdingerb** [comment]
Yeah... it's an issue of the QL window being 'always-on-top'.
I tried a quick hack of changing the feel to 'normal' as soon as the user starts dragging an item. While that does work, the window will then stay 'normal', because QL isn't informed when the user drops the item somewhere outside the app.
Unsatisfactory...

Equally unsatisfactory work-around: open the Setup window before trying to d&d an item to e.g. Launchbox... :)

**Comment by diversys** [comment]
While the work-around works it's counter intuitive :)

**Comment by diversys** [comment]
My use case was to drop freshly compiled Haiku's Pulse to Terminal which didn't work.
