### ISSUE TITLE
QuickLaunch alway on top problem

### ISSUE THREAD

**Issue by diversys** [humdingerb/quicklaunch#32]
Current QuickLaunch behaviour doesn't let me interact with other windows, I can only move them around and that's basically it. I just somehow deadlocked QuickLaunch (by adding libbe.so to ignore list using context menu) and have no way to quit it. 

Well, I can probably probably use Team Monitor to do that but since I'm in a VM Ctrl+Alt+Del doesn't work for some reason. So I guess this behaviour needs to be rethink. I think it wasn't like that in some prior version but maybe I remember it wrong?

**Comment by humdingerb** [comment]
You remember correctly. I removed the option because it simplifies dealing with the setup window and file dialogs. I didn't deem the option worthwhile, because the normal use case is to quickly summon QuickLaunch, find an app and dismiss QuickLaunch. Having the QL window modal for that short a time shouldn't be annoying in any case.

You're correct, the TeamMonitor would solve a frozen QL window.
Which is the real bug here: Why does QL hang in this case? I have  /system/servers/libs/* in my ignore list and also see QL hang when trying to remove it... I'm looking into that... soon... ish...

**Comment by diversys** [comment]
It is impossible to drag'n'drop to ignore list of Settings window now.

**Comment by humdingerb** [comment]
Damn, I haven't tested that... :)
With the latest commit the MainWindow becomes 'normal' when the SetupWindow is open - allowing your to browse the system to d&d files and use the file dialog of the "Add..." button - and reverts to being 'modal' when the SetupWindow is closed.
Good compromise? (I smell another release coming... :) )
