### ISSUE TITLE
Consistency suggestion for translation string

### ISSUE THREAD

**Issue by andreibosco** [humdingerb/quicklaunch#40]
I've started the pt_BR for quicklaunch and I have one small suggestion for this string:
```
QuickLaunch %version%\n\twritten by Humdinger\n\tCopyright %years%\n\nQuickLaunch quickly starts any installed application. Just enter the first few letters of its name and choose from a list of all found programs.\n
```
All other strings uses the term 'application', but this one uses both 'application' and 'programs'. For consistency sake, I suggest renaming 'programs' to 'applications'.

**Comment by humdingerb** [comment]
Agreed. I'm changing the code anyway to use a regular BAboutWindow and will change that while I'm at it.
Thanks.

**Comment by andreibosco** [comment]
Follow up: I've noticed that the original string was updated on polyglot but it didn't tag the translated string as fuzzy or 'needs updating' (first time using Polyglot so I'm not sure that's supported).

**Comment by humdingerb** [comment]
Polyglot doesn't do fuzzy. :)
In this particular case, I changed that sentence in the AboutWindow to remove the copyright and version info. Only the last sentence stayed the same (or rather the English version uses only "application" instead of the "application/programs" mix, as you suggested).
I updated the catkeys at Polyglot and removed the copyright/version part for all languages myself to avoid having to wait for all re-translations.
