### ISSUE TITLE
Auto close after a time

### ISSUE THREAD

**Issue by blackjack75** [humdingerb/quicklaunch#44]
It would be nice if quicklaunch auto closed after a set amount of time.

It often happened to be that I left it open and with a dozen other windows on screen I don't even see the UI is locked up because of QuickLaunch intercepting all keys.

If it closed automatically after 120 seconds of inactivity it would solve the issue.

**Comment by humdingerb** [comment]
It happens to me as well sometimes. :)
But almost never after 2 minutes, but much sooner. So the suggested solution would only work for the very rare occasions I wasn't doing anything with the computer for that long.

The QL window is already modal, it's floating above all windows on all workspaces. Not much more to do here, I think. Maybe Haiku itself could make these windows even more "in your face", maybe by dimming all other windows? But I suspect that isn't easily done with a non-compositing app_server, I imagine...

**Comment by blackjack75** [comment]
Yes I agree something the OS should do. For example it could just turn the background grayscale / dimmer indeed.

I am not sure where in trac I should open a ticket for that. Any idea  ? 

In the meantime I think the app itself could (optionally just show a large black window with 20% (?) opacity together below the search window.

I was a big fan of quicksilver on Mac a long long time ago, in PowerPC times. I still run it on my beloved G4 Cube :-) 

I think the reason it didn't happen was because the QuickSilver window was quite different.  So you would never mix it up with a normal small window from a search box in your text editor.

Maybe showing the same huge icon (optionally0) would help solve this. I was also right in the middle of the screen. At a time of course when we had smaller screens. I checked and QuickSilver didn't affect the whole background and I don't remember this being an issue.

![quicksilver-screenshot](https://github.com/user-attachments/assets/b704c396-a014-4dfd-b477-73df700bbc4e)

**Comment by humdingerb** [comment]
Never used MacOS, but these are some massive icons... :)

In any case, this issue has become a non-issue. In the next release, the QuickLaunch window won't be modal anymore, but will just float over all other windows. That means that users can move it aside and interact with other apps/windows. This is necessary, because input methods of e.g. Japanese wouldn't quite work if QuickLaunch were still hugging the focus.

If you want to submit an enhancement ticket at Haiku's Trac to "dim" all other windows (+Desktop) when there's a modal window, the correct category should be the "app_server".

**Comment by blackjack75** [comment]
Thanks!

For reference I opened a ticket here:
https://dev.haiku-os.org/ticket/19189#ticket
