### ISSUE TITLE
Update results on the fly

### ISSUE THREAD

**Issue by diversys** [humdingerb/quicklaunch#5]
- Search for an app
- Move app to Trash
- Notice that path is not updated

**Comment by humdingerb** [comment]
QuickLaunch, for better or worse, is a modal window, which prevents interacting with most things outside its window. (There's a "hack" though: show the Setup window, and QuickLaunch becomes "un-modal". :) )
This is OK in my book, because QuickLaunch is supposed to be only quickly invoked to launch an app and not to be open for a longer time while doing other things.

Therefore implementing node-monitoring or similar techniques to solve the described feature isn't really worth the effort, I think.
