### ISSUE TITLE
greyed AddRemoveFavorite entry

### ISSUE THREAD

**Issue by Briseur** [humdingerb/quicklaunch#54]
At opening, when nothing has been typed yet, there's a greyed AddRemoveFavorite entry in Selection menu. 
It seems to be a placeholder for Add to favorite / Remove from favorite entry that appear later.
It would be nice to make it not appearing but if that's not possible perhaps it should be translatable.

**Comment by humdingerb** [comment]
Thanks for reporting, I didn't notice it...
I went with just defaulting to "Add to favorites". Once you've removed the last favorite, it stays on the last used label, "Remove favorite". But it doesn't really matter, because the whole "Selection" menu is disabled then anyway.
Still, it should of course say something sensible, and it does now.
